import {useEffect,useRef,useState} from "react";
import {api} from "../lib/api.js";
import {useAuth} from "../context/AuthContext.jsx";
import {useToast} from "../context/ToastContext.jsx";
import {ATTRS,ATTR_LABELS,DIFFICULTIES} from "../lib/rpg.js";
import {Field,Meter,Modal,Panel,Skeleton,useTitle} from "../components/ui.jsx";
const EMPTY={name:"",category:"MIND",difficulty:"STANDARD"};
export default function Quests(){
 useTitle("Deeds — EMBERHOLD"); const {patch}=useAuth(); const toast=useToast(); const [items,setItems]=useState(null); const [err,setErr]=useState(""); const [editor,setEditor]=useState(null); const [form,setForm]=useState(EMPTY); const [busy,setBusy]=useState(false); const [rank,setRank]=useState(""); const [float,setFloat]=useState(null); const timer=useRef(null);
 const load=()=>{setErr("");setItems(null);api.quests().then(d=>setItems(d.quests)).catch(e=>setErr(e.message))}; useEffect(load,[]);
 function open(q){setForm(q?{name:q.name,category:q.category,difficulty:q.difficulty}:EMPTY);setEditor(q||{})}
 async function save(e){e.preventDefault();if(!form.name.trim())return toast({tone:"bad",title:"Name required",body:"Give the deed a name."});setBusy(true);try{if(editor?.id){const d=await api.updateQuest(editor.id,form);setItems(x=>x.map(q=>q.id===editor.id?d.quest:q));toast({title:"Deed amended"})}else{const d=await api.createQuest(form);setItems(x=>[d.quest,...x]);toast({title:"Deed posted",body:`Pays ${d.quest.xp} XP and ${d.quest.credits} crowns.`})}setEditor(null)}catch(e){toast({tone:"bad",title:"Could not save",body:e.message})}finally{setBusy(false)}}
 async function complete(q,e){const r=e.currentTarget.getBoundingClientRect();setFloat({x:r.left+r.width/2,y:r.top});setItems(x=>x.map(a=>a.id===q.id?{...a,pending:true}:a));try{const d=await api.completeQuest(q.id);setItems(x=>x.filter(a=>a.id!==q.id));patch(d.user);toast({title:`+${d.xp} XP · +${d.credits} crowns`,body:q.name});if(d.rankUp)setRank(d.user.rank)}catch(e){setItems(x=>x.map(a=>a.id===q.id?{...a,pending:false}:a));toast({tone:"bad",title:"Not recorded",body:e.message})}setTimeout(()=>setFloat(null),900)}
 async function remove(q){if(!confirm(`Strike "${q.name}" from the board?`))return;const old=items;setItems(x=>x.filter(a=>a.id!==q.id));try{await api.deleteQuest(q.id);toast({title:"Deed struck"})}catch(e){setItems(old);toast({tone:"bad",title:"Delete failed",body:e.message})}}
 return <div className="page"><div className="page-head"><div><p className="kicker">Your active commitments</p><h1>Deed Board</h1></div><button className="btn primary" onClick={()=>open()}>+ Post deed</button></div>
 {err&&<Panel className="error-strip"><span>{err}</span><button className="btn" onClick={load}>Retry</button></Panel>}
 {items===null&&!err?<div className="stack"><Skeleton height={74}/><Skeleton height={74}/><Skeleton height={74}/></div>:items?.length?items.map(q=><article className={`quest ${q.pending?"pending":""}`} key={q.id}><div><h2>{q.name}</h2><div className="tags"><span>{DIFFICULTIES[q.difficulty].label}</span><span>{ATTR_LABELS[q.category]}</span><span>{q.xp} XP · {q.credits} CR</span></div></div><div className="quest-actions"><button className="btn primary" disabled={q.pending} onClick={e=>complete(q,e)}>Fulfil</button><button className="btn" onClick={()=>open(q)}>Amend</button><button className="btn danger" onClick={()=>remove(q)}>Strike</button></div></article>):<Panel className="empty"><h2>The board is bare.</h2><p>Post your first real-world deed and make it count.</p><button className="btn primary" onClick={()=>open()}>Post a deed</button></Panel>}
 {float&&<span className="xp-float" style={{left:float.x,top:float.y}}>+XP</span>}
 {rank&&<div className="rank-overlay" role="dialog" aria-modal="true"><div className="rank-card"><p className="kicker">A new banner is raised</p><h2>{rank}</h2><div className="stripes"/><p>Your deeds have earned a new rank.</p><button className="btn primary" onClick={()=>setRank("")}>Continue</button></div></div>}
 {editor!==null&&<Modal title={editor?.id?"Amend deed":"Post deed"} onClose={()=>setEditor(null)}><form onSubmit={save}><Field id="qname" label="Deed name"><input id="qname" maxLength="80" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field id="qcat" label="Attribute"><select id="qcat" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{ATTRS.map(a=><option key={a} value={a}>{ATTR_LABELS[a]}</option>)}</select></Field><Field id="qdiff" label="Difficulty"><select id="qdiff" value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})}>{Object.entries(DIFFICULTIES).map(([k,v])=><option key={k} value={k}>{v.label} — {v.xp} XP / {v.credits} CR</option>)}</select></Field><Meter value={DIFFICULTIES[form.difficulty].xp} max={100} label="Reward size" segments={10}/><div className="modal-actions"><button className="btn primary" disabled={busy}>{busy?"Saving…":"Save deed"}</button><button type="button" className="btn ghost" onClick={()=>setEditor(null)}>Cancel</button></div></form></Modal>}
 </div>
}